# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SUI

  pod 'SwiftLint'

  target 'SUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SUIUITests' do
    # Pods for testing
  end

end
